
services:
  # Backend Web Service
  - type: web
    name: threadsy-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: CLOUDINARY_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: Admin_EMAIL
        sync: false
      - key: Admin_PASSWORD
        sync: false
      - key: FRONTEND_URL
        sync: false

  # Frontend Static Site
  - type: static
    name: threadsy-frontend
    plan: free
    rootDir: frontend
    buildCommand: "npm install && npm run build"
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_BACKEND_URL
        fromService:
          type: web
          name: threadsy-backend
          property: url

  # Admin Static Site
  - type: static
    name: threadsy-admin
    plan: free
    rootDir: admin
    buildCommand: "npm install && npm run build"
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_BACKEND_URL
        fromService:
          type: web
          name: threadsy-backend
          property: url
